### ISSUE TITLE
Command to output supported function signatures

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#1]
There are tools out there (autocomplete, live doc, etc) that consume a list of function signatures in a regular format - it'd be good to output one. Eventually we can think about what else a presentation compiler would look like.

**Comment by bob-carpenter** [comment]
This is already being done through the documentation to do things like autocomplete in R.

Did you want more of a complete solution from the function signatures that has all the gazillion instantiations of each function by type?

**Comment by seantalts** [comment]
I believe you need to combine the information from the documentation with the information from the compiler to e.g. generate explicit C++ template instantiations. I think it could be good to eventually have an API that toolkit developers can query for autocomplete and whatnot, and emitting the functions seems like a decent first step instead of using the list from the documentation (which is edited by hand and could differ from what’s actually allowed).

**Comment by VMatthijs** [comment]
If you guys give me a format you'd like this is, it'd be easy for me to implement.

**Comment by bob-carpenter** [comment]
This is already being generated as part of the doc for R.  But it's with placeholders for arguments because there are a gazillion instantiations of the lpdfs.    If you need Stan instantiations (real vs. int, etc.) other than C++ (double, int, var, etc.), you should be able to generate from however the function signatures are represented.
