### ISSUE TITLE
stancjs - reset counter for optimization

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#1117]
I am not 100% where this is coming from or if would actually lead to a problem for the end-user, but I am guessing there is some global state that holds an integer that is used to create temporary variables in optimization. If this is fine feel free to close this.

This obviously only comes up with stancjs, with the binary version there is no leftover state.

If I compile a model with optimization and pretty print the optimizer MIR I get:
```stan
  real foo(data array[,] real x, array[] int y, vector beta, int N, int K) {
    data matrix lcm_sym2__;
    data real lcm_sym1__;
    {
```

Then after compiling the exact same a few more I get:
```stan
functions {
  real foo(data array[,] real x, array[] int y, vector beta, int N, int K) {
    data matrix lcm_sym57__;
    data real lcm_sym56__;
    {
```

**Comment by WardBrian** [comment]
I believe it’s in src/common/GenSym.ml

This should be harmless, but we probably should do a scan of the code base and make sure any mutable state is correctly reset each time

**Comment by WardBrian** [comment]
Here is a gist of all the mutable state:

https://gist.github.com/WardBrian/fc00ff95b56b5c77491df390b3ec4655

This is pretty easy to grep for - it will all be tied to the `ref` keyword, the `mutable` keyword in records (not used anywhere in stanc3), and then either `Hashtbl` or `Table` mutation. There is also `Array`, which is only really used in the return helpers for stancjs.

Some notes:
1. All the entries in stanc.ml are trivially fine, since the binary exits between runs
2. Doing this I've immediately spotted a "bug": info doesn't clear it's list of included files/paths. Of course, for stancjs this is always empty anyway.
3. We have a bunch of mutable state around warnings and basically none of it gets cleared. For example in the typechecker, running code that emits a warning such as 
  ```stan
  generated quantities {
   int x, w;
  int z = x / w;
  }
  ```

  Means this warning will persist forever. 
4. I believe the table `map_rect_calls` is never cleared after it is created. Not sure if this is benign or not
5. As discussed in the original issue, `GenSym` never gets reset to 0.

The remaining usages all look fine to me, though I haven't looked much at the ones that exist in the optimization code alone
