### ISSUE TITLE
Allow tilde statements in generated quantities as synonyms for rng assignment

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/stanc3#1136]
It would be pretty easy to translate something like 

```stan
generated quantities {
  vector[N_tilde] y_tilde;

   y_tilde ~ normal(alpha + beta * x_tilde, sigma);
}
```

to the equivalent of the current 

```stan

generated quantities {
  vector[N_tilde] y_tilde;

   y_tilde = normal_rng(alpha + beta * x_tilde, sigma);
}
```

Is there a reason we don't do this? I think one of the friction points of Stan to new users is the fact that generating looks so different from the model blocks and it's hard to move code back and forth between them.

**Comment by nhuurre** [comment]
I'm against this. One of the most common misconceptions is that tilde statements draw samples in the model block. If you search for `Rejecting initial value` on the forum you'll find many models that apply a tilde statement to an uninitialized variable, expecting it to assign a value. Allowing that syntax to be correct outside the model block would just create more confusion.

I am in favor of redesigning the whole language to be more like [SlicStan](https://github.com/mgorinova/SlicStan) but I don't see that happening anytime soon.

**Comment by WardBrian** [comment]
This suggestion was partially prompted by a discussion @bob-carpenter and I had recently of a SlicStan-esque blockless style

Your point is well taken though, I’m not sure if this is productive outside that larger change

**Comment by bob-carpenter** [comment]
@nhuurre is absolutely right that this distinction between `~` as RNG and `~` as increment log density is one of the most confusing aspects of Stan for users.  I'm not sure that adding `~` in generated quantities would make this worse, but there's definitely potential for increased confusion.

One thing we might be able to solve with `~` in generated quantities is the homogeneity of the RNG return type.  For vectorized RNGs, it always returns arrays.  So what I find myself having to write is something like this to put it on one line,

```
vector[N] x = to_vector(normal_rng(rep_vector(mu, N), sigma));
```

whereas I'd much rather write

```
vector[N] x ~ normal(mu, sigma);
```

and let the compiler sort it out.

**Comment by betanalpha** [comment]
+1 to not abusing ~.

I also agree that the array return type of the PRNGs is often a pain.  Is this a narrow enough circumstance that the compiler could safely infer a PRNG in a declare and assign and automatically do the conversion?

**Comment by bob-carpenter** [comment]
> Is this a narrow enough circumstance that the compiler could safely infer a PRNG in a declare and assign and automatically do the conversion?

If it was just a declare and define, then yes.  But I'm even less keen to make a special case out of `=` than `~`.  

What we could do in more generality is allow assignment of any conforming structure.  That's how we do I/O in Python and R, after all.  That is, we'd allow things like:

```stan
row_vector u[10];
vector v[10];
array[10] real w;
u = v;  u = w; v = u; v = w; w = u; w = v;  // all would be legal
```

And then we'd want to maintain the parallel between assignment and function calling to allow function args to act the same way.

I think the main thing we'd have to worry about is ambiguity in overloaded function definitions.  For example, we have `row_vector * vector` and `vector * row_vector` and they produce a `real` and `matrix` respectively.  If I try to pass in two arrays here, or two `vector` types, you wouldn't be able to resolve.  So that might just be a compiler error that the user would have to fix by explicitly casting.

**Comment by WardBrian** [comment]
Making that change for assignment would be really simple on the compiler end, we would just need to change the implementation of stan::assign in C++. For promotion, it would be a lot messier I believe, but not impossible (again, with the same caveats about ambiguity)

I suppose at some point the question is why maintain the distinction if you allow any of them to be used everywhere? But that’s a sort of major-version very-incompatible redesign

**Comment by bob-carpenter** [comment]
> why maintain the distinction if you allow any of them to be used everywhere?

In retrospect, I wish the internal representations were the same.  If you don't distinguish between row vectors and column vectors you need a way to distinguish them in linear algebra functions because `row_vector * vector` is a very different operation than `vector * row_vector`.

R overloads, but then if you create a 1D array and transpose it, you get a 2D array.  

```R
> a <- c(1, 2, 3)
> t(a)
     [,1] [,2] [,3]
[1,]    1    2    3
```

That hints at the other solution, which is to only define linear algebra for matrices.  Then you can represent vectors, row vectors, and matrices as 2D arrays.  Vectors are just (M x 1) and row vectors (1 x N).  The inconvenience there is that row vector * vector now produces a 1 x 1 matrix, so you have to extract elements out of it as it won't act like a scalar if it's a 1 x 1 matrix.  But I do think this is probably the easiest solution for everything we do.  It would've hugely simplified the number of linear algebra signatures we needed.  I think it might be a little bit less efficient---Eigen specializes the constant (1 x N) and (M x 1) structures.

**Comment by WardBrian** [comment]
Since it seems like a pretty solid consensus not to do this I'm going to close the issue. We can open others to discuss things like the rng return types.
