### ISSUE TITLE
ForEach loop not translated properly to MIR

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#121]

**Comment by seantalts** [comment]
Can you pull in the description of the issue and @bob-carpenter's code if it exists?

**Comment by seantalts** [comment]
Looking at the code and your comments on the PR I'm still not sure what's wrong with what is going on - re: matrices - those should be indexed appropriately even by a single variable, because Eigen allows for that, assuming that we're promising users to iterate through a matrix in the same order that Eigen does.

**Comment by bob-carpenter** [comment]
I don't know what code is being generated, but if it works for vectors and not matrices, maybe you're trying to use operator[] instead of the more general operator().

**Comment by VMatthijs** [comment]
Never mind. I think there may not be a problem after all, other than that row_vector expressions are not implemented yet. I'm going to close this. Sorry for the distraction!
