### ISSUE TITLE
[BUG] Array declaration no longer canonicalizes from deprecated format

### ISSUE THREAD

**Issue by bamarco** [stan-dev/stanc3#1410]
### Current Behavior:

when I run this command on code with a deprecated array declaration:
```sh
stanc array-deprecation-error.stan --canonicalize=deprecations
```
it produces the error:
```
Syntax error in 'array-deprecation-error.stan', line 8, column 15 to column 16, parsing error:
   -------------------------------------------------
     6:  data {
     7:    int an_int;
     8:    int some_ints[an_int]; // problem here
                        ^
     9:  }
   -------------------------------------------------

";" expected after variable declaration.
```
### Expected Behavior:

Convert deprecated code to:
```stan
data {
  int an_int;
  array[some_ints] int an_int; // problem here
}
```

### Model Code

<details><summary>Model which exhibits the issue</summary>
stanc3 v2.34.0 (Unix)

worked in a previous version (unsure which one)

```stan
// Please put your code here
data {
  int an_int;
  int some_ints[an_int]; // problem here
}
```
</details>

**Comment by WardBrian** [comment]
Deprecations are only guaranteed to be formattable during the warning window and for one version after removal. For the array syntax that means you can use any compiler from 2.26-2.33, but not 2.34, as the code for handling the old syntax has been removed

**Comment by rtrangucci** [comment]
Is it possible to create a tool that can reformat old array syntax that is packaged with the current stanc3 releases? I've got many large old stan files with the deprecated array syntax. Reformatting by hand would take a long time and be error prone. In order to use the code reformatting I have to switch stanc3 versions to reformat the code, which can be complicated by figuring out how to compile old ocaml versions. I'm sure I'm not the only user that has run into this issue.

**Comment by WardBrian** [comment]
@rtrangucci you can always download an older build from e.g. https://github.com/stan-dev/stanc3/releases/tag/v2.32.2 and use that on older files. If we provided a tool to do this, it would probably just be that version of the compiler with some unnecessary features removed, so it is hopefully just as good?
