### ISSUE TITLE
AST locations should support #includes

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#20]
Right now AST locations are:

```ocaml
type location =
  | Location of Lexing.position * Lexing.position  (** delimited location *)
  | Nowhere  (** no location *)
...
type position = {
  pos_fname : string;
  pos_lnum : int;
  pos_bol : int;
  pos_cnum : int;
}
```

This doesn't seem to support the include use case where a statement comes from a file but may have been included by other files (unless I'm thinking about this wrong).

**Comment by VMatthijs** [comment]
It currently has all the include information as well, but appended to the filename. I did it that way because ocamllex and menhir are very restrictive in their communication channel. (Basically, a single value of type Lexing.position.) It's a bit hacky, but would do the trick. I still plan to insert the line number and column into the include backtrace (currently, it's just a backtrace of file names). I could clean things up a bit by just writing encoding and decoding functions for storing the whole include backtrace in the filename string.

Feel free to rewrite it to something better if you have ideas, though.

If this is something you urgently need, please let me know. Otherwise, I will continue working on preparing my POPL talks for the next few days.

**Comment by seantalts** [comment]
As we spoke about, we need to alter the existing stuff to produce backtraces. Even if we go with a single location string from the AST for now (to be fixed later if performance is an issue), I'm not sure why there are two Lexing.positions (almost certainly not the data structure we want to end up using).

**Comment by seantalts** [comment]
This won't block anything, really - I will just assume we are using a single string and fake it for now.

**Comment by seantalts** [comment]
(But if we will end up with a different data type, knowing now would save me time).

**Comment by VMatthijs** [comment]
If you're happy with a single string, let's stick with that.

I opened an issue for this a while back: https://github.com/stan-dev/stanc3/issues/7

**Comment by seantalts** [comment]
That works. I want to also track that we should update the type of locations to more closely match what we need when generating error messages.

**Comment by VMatthijs** [comment]
After discussion, we decided that just the AST should be updated to not be hacky. For now the hack will remain in the parser.

**Comment by VMatthijs** [comment]
This should be fixed by PR https://github.com/stan-dev/stanc3/pull/36
