### ISSUE TITLE
Help with simple expect test

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#299]
Just trying to write an expect test for [`add_int_index`](https://github.com/stan-dev/stanc3/blob/master/src/middle/Middle.ml#L170)

```ocaml
let add_int_index e i =
  let mtype = infer_type_of_indexed e.emeta.mtype [i] in
  let expr =
    match e.expr with
    | Var _ -> Indexed (e, [i])
    | Indexed (e, indices) -> Indexed (e, indices @ [i])
    | _ -> raise_s [%message "These should go away with Ryan's LHS"]
  in
  {expr; emeta= {e.emeta with mtype}}

let%expect_test "adding integer index" = 
 let idx s = 
   Single {expr= Var s; emeta= {mtype= UInt; mloc= no_span; madlevel= DataOnly}}
 in 
  let decl_var =
  { expr= Var "test_val"
  ; emeta= {mloc= no_span; mtype= UInt; madlevel= DataOnly} } in
  Fmt.(strf "@[%a@]" (list ~sep:comma Pretty.pp_unsizedtype) (add_int_index decl_var (idx "foo"))) |> print_endline;
  [%expect {||}]
```

When I run `dune runtest src` it tells me

```
File "src/middle/Middle.ml", line 198, characters 0-3:
Error: Syntax error
```

The actual error is that I'm using the wrong pretty print 

```
This expression has type mtype_loc_ad with_expr
but an expression was expected of type unsizedtype sexp_listm
```

What do I use to print out `mtype_loc_ad with_expr` types?

**Comment by seantalts** [comment]
`  Fmt.(strf "@[%a@]" Pretty.pp_expr_typed_located (add_int_index decl_var (idx "foo"))) |> print_endline;`

`add_int_index` returns an expression, so you just need to pretty print an expression. And for a typed and located expression we have `Pretty.pp_expr_typed_located` (that's a mouthful! Micky is going to do a unifying refactor on the MIR and AST I think, so hopefully some of these names become standardized).

The test as written will fail because you can't index into an integer. You can change `test_val`'s type to a container type to fix that.

**Comment by seantalts** [comment]
```
 |let%expect_test "adding integer index" =
 |  let idx s =
 |    Single {expr= Var s; emeta= {mtype= UInt; mloc= no_span; madlevel= DataOnly}}
 |  in
 |  let decl_var =
 |    { expr= Var "test_val"
 |    ; emeta= {mloc= no_span; mtype= UArray UInt; madlevel= DataOnly} } in
 |  Fmt.(strf "@[%a@]" Pretty.pp_expr_typed_located (add_int_index decl_var (idx "foo"))) |> print_endline;
-|  [%expect {||}]
+|  [%expect {| test_val[foo] |}]
```

**Comment by SteveBronder** [comment]
Cool ty!
