### ISSUE TITLE
Set up ocamldoc to generate doc for stanc3

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#312]
https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html

Hopefully we can publish it somewhere on github pages like we do for math: http://mc-stan.org/math/

**Comment by SteveBronder** [comment]
I started taking a look at this, specifically trying reading the stuff in dune docs about being able to run [`dune build @doc`](https://dune.readthedocs.io/en/stable/documentation.html). Running into a couple weird issues

1. The folders are currently made into private libraries 
- This means `dune build @doc` won't generate any of the docs for these. Running `dune build @doc-private` does generate the docs for these, but it makes each library as a separate 'site' i.e. frontend gets it's own index.html ala

```
_build/default/_doc/_html/frontend@stanc/Frontend/index.html
```

If we can figure out a way to collate all these private library docs together, like hand make one index.html that points to all these that would be nice, though I don't see anything online for that. One solution would be to use [`include_subdirs`](https://dune.readthedocs.io/en/stable/dune-files.html#library) instead of private libraries to make one big package instead of a bunch of smaller private ones. Though idk the intricacies involved in the pros/cons of private libs vs. subdirs but can look into it if that would work for everyone. idt it's as simple as 'move all the stuff from the smaller dune files into the larger dune files' but it might be easy'ish like that

2. `dune build @doc` makes an index.html but it's empty

- I'm not sure why but running the above does that. We have doc strings in stanc3 that should be doc'd. I think I just need to go read other projects to see how their docs are done

Could we get away with having an index.md in a `/doc` file that points to the index.html files for the private libraries? That feels like a fine/shotgun approach to get docs up since we can just have jenkins do `make docs-private` to push up new docs

**Comment by SteveBronder** [comment]
Oh also there's a thread [here](https://discuss.ocaml.org/t/the-state-of-ocamldoc-and-odoc/244/31) with another project getting (1) and (2). He shows the commit that fixes the docs for him, it looks like we would have to have a /bin folder with a `main.ml` that would then call stanc. Though idt his solution get's around the private libraries thing

**Comment by seantalts** [comment]
I think we probably want to keep the different libraries separate to some extent? @enetsee might be able to speak more intelligibly about that, but it's not obvious to me that we'd want to have every module listed on a single page vs using a hierarchy we find useful for organizing the code (I'd be open to changing the code hierarchy on its own merits but probably not for the sake of easier autogeneration of doc). None of the generated ocaml doc I've seen is great, but we can look at a few examples : https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/index.html
and 
https://erratique.ch/software/fmt/doc/

FWIW Dune also tends to rely very heavily on subdirectories as semantically important structure, so I'm not sure it will be easy to mess around with the dune files in that way, but you can try.

Looking at that commit it is not at all obvious to me what the problem was, lol. He did a few different things including moving a file from lib to bin... We have multiple binaries in stanc3; maybe we should move them to `/bin`? @enetsee has been the one doing most of the organizational stuff here, I'm hoping he can jump in here and tell us how this should work :)

**Comment by enetsee** [comment]
The reasoning behind the current directory structure stems from trying to enforce clear interfaces between the existing compiler phases and separating things which are not core to the compiler (specifically `common` contains a interfaces and functors which should really end up in their own libraries separate from stanc3). 

Long term this structure is also useful in supporting multiple frontends and backends (for example, we already have initial versions of a stan-math and tfp backend). To add a little more context to what I'm thinking here, `middle` is meant to contain the core IR(s), functions for operating on them and the interfaces for `frontend`s and `backend`s and functors for constructing compilers from modules implementing these interfaces. If you look at [`Compiler.ml`](https://github.com/stan-dev/stanc3/blob/master/src/middle/Compiler.ml) there is a sketch of what this may ultimately look like. 

Following this line of thinking, we may ultimately want to publish these libraries separately. Since each frontend and backend could (potentially!) expose its own set of compiler options the API documentation _should_ live with those libraries. 

Each compiler 'driver' (i.e. a particular instance of the `Compiler` module signature, responsible for IO) would refer to the particular frontend and backend libraries as well as `middle` but it may be we want some additional overarching document which could tie together the docs for each?

All of that being said, I'm not sure there was a clear decision that what I proposed was structure we had settled on so we maybe we  should nail that down before moving things around?

**Comment by seantalts** [comment]
I think that structure seems pretty good, if possibly on the more granular side of the spectrum. I think the reality is that this compiler will have separate folders for a few organizational purposes, and if we want to generate ocamldoc we have to deal with that somehow. I'll add taking a look at this to my list, or Steve if you want any particular help with it let me know. Seems worth investing in getting something reasonable up on the github pages for stanc3.

**Comment by SteveBronder** [comment]
Circling back around to this because I'd still like a docs page. Are we going to break up the different pieces into other packages? If that's not on a time schedule then tbh I'd prefer we make them public. 

> Long term this structure is also useful in supporting multiple frontends and backends (for example, we already have initial versions of a stan-math and tfp backend). To add a little more context to what I'm thinking here, middle is meant to contain the core IR(s), functions for operating on them and the interfaces for frontends and backends and functors for constructing compilers from modules implementing these interfaces. If you look at Compiler.ml there is a sketch of what this may ultimately look like.

I'm not sure I understand some mechanics here as my ocaml-fu is weak, but if these were included as modules in stanc3 would folks writing other backends just be able to import `Stanc.Ast`, `Stanc.Mir`, etc without breaking them up into multiple package?

I was going to work on writing docs today but then figured idt there's not as much of a point to docs if they are not nicely exposed.

**Comment by SteveBronder** [comment]
I reached out to the dune folks and it looks like it might be possible to make the private docs as a github page when using `dune-release` do we use that for our nightly builds? If so then as long as the docs files show up in a `man` folder I can write an index.html file to link them all together

https://github.com/ocaml/dune/issues/4337#issuecomment-796255981

**Comment by WardBrian** [comment]
#1006
