### ISSUE TITLE
How does `all` work in Fixed or Fixed.Pattern?

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stanc3#370]
I was under the impression that a cool thing about the `all` recursion scheme(?) was that you only had to define it over the pattern and not handle recursion yourself. I wrote the following expecting it to be run on all expressions:
```ocaml
let typecheck_funapps (e : Expr.Typed.t) =
  let is_valid_sig args f =
    Stan_math_signatures.get_fun_or_op_rt_opt f args |> Option.is_some
  in
  Expr.Fixed.Pattern.all e.pattern ~init:true ~pred:(fun e ->
      match e.Expr.Fixed.pattern with
      | FunApp (Fun_kind.StanLib, f, args) ->
          List.exists ~f:(is_valid_sig args) (to_stanlib_fnames f)
      | _ ->
        true )
```

But I am pretty sure it is not run on all expressions. Any ideas for what I'm doing wrong? Do I just need to do the recursion myself for both `_` and `args`?

**Comment by seantalts** [comment]
This seems to work:
```ocaml
let typecheck_funapps (e : Expr.Typed.t) =
  let is_valid_sig args f =
    Stan_math_signatures.get_fun_or_op_rt_opt f args |> Option.is_some
  in
  let rec funapp_check e =
    match e.Expr.Fixed.pattern with
    | FunApp (Fun_kind.StanLib, f, args) ->
        List.for_all ~f:funapp_check args
        && List.exists ~f:(is_valid_sig args) (to_stanlib_fnames f)
    | e -> Expr.Fixed.Pattern.all e ~init:true ~pred:funapp_check
  in
  funapp_check e
```

**Comment by enetsee** [comment]
So `all` is part of `Foldable` and is unrelated to recursion schemes.

For `Pattern.S` types, `all` takes a predicate and applies it to each 'slot' in the pattern so it's not doing any recursion (pattern's are meant to be non-recursive). 

The `Foldable` interface is included in our `Fixed` interface but since our encoding is _parametric in the type of meta-data_   all of it's operations are working on the type of meta data rather than patterns (this is true for map, too). It will do the recursion for you but not to the part you want to work with in your example!

In the sketches I've been making for type checking I've adopted a [bi-directional type checking approach](https://www.youtube.com/watch?v=utyBNDj7s2w) which is a way of writing a type checker that works even with quite sophisticated type systems. The SlicStan paper also uses this approach, given as the 'algorithmic typing rules'.  

(I wrote a sketch of the example in the video [here](https://sketch.sh/s/5Ojzpr927ieZQXqzMxR7r9/).)

When you have a fixed-point representation of terms, a bi-directional checker can be written in terms of the `fold_pattern` recursion scheme which is the generalization of `rewrite_bottom_up`.

```ocaml
val fold_pattern : f:('a * 'r Pattern.t -> 'r) -> 'a t -> 'r
```

The way this works is to go all the way down the terminal nodes in your expression and apply the function `f`. Now when you go back up the tree, all of the 'slots' in the `Pattern` have been replaced with the type `'r`. For a type-checker, these would need to be something like `UnsizedType.t option` since e.g. we need the types of types of the functions arguments to type check the function application, and we need some way of encoding failure.
