### ISSUE TITLE
Extend the size function to support all Stan objects

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#402]
Currently `size()` in the Stan language only support vectors (see below, in the math size only support `std::vector<T>` input). After/If https://github.com/stan-dev/math/pull/1514 is merged `size()` will also support scalars & matrices in Math. Do we need that functionality in the language?

Currently supported signatures:
```
int size(int[])
int size(real[])
int size(vector[])
int size(row_vector[])
int size(matrix[])
int size(int[,])
int size(real[,])
int size(vector[,])
int size(row_vector[,])
int size(matrix[,])
int size(int[,,])
int size(real[,,])
int size(vector[,,])
int size(row_vector[,,])
int size(matrix[,,])
int size(int[,,,])
int size(real[,,,])
int size(vector[,,,])
int size(row_vector[,,,])
int size(matrix[,,,])
int size(int[,,,,])
int size(real[,,,,])
int size(vector[,,,,])
int size(row_vector[,,,,])
int size(matrix[,,,,])
int size(int[,,,,,])
int size(real[,,,,,])
int size(vector[,,,,,])
int size(row_vector[,,,,,])
int size(matrix[,,,,,])
int size(int[,,,,,,])
int size(real[,,,,,,])
int size(vector[,,,,,,])
int size(row_vector[,,,,,,])
int size(matrix[,,,,,,])
```

**Comment by seantalts** [comment]
@bob-carpenter what do you think? It seems like in Stan there are a lot of places where we intentionally have choosen to make people choose different functions based on the types they're working with, even when the semantics are obvious. I think in some cases this is because the old type system was simple and bottom up - so we needed to know if someone was trying to build an vector vs an array with e.g. `rep_vector` vs `rep_array`. In this case, `size` always returns an integer so it seems fine to extend its inputs if that's the only reason for those choices, but I'm not sure it was.

**Comment by bob-carpenter** [comment]
> Currently size() in the Stan language only support vectors (see below). After/If stan-dev/math#1514 is merged size() will also support scalars & matrices in Math. 

Yes.  We should definitely add a generic size function for all Stan objects.  It should even return 1 for scalars.  We can cross the complex number bridge if and when it gets to the language.

**Comment by bob-carpenter** [comment]
> On Dec 20, 2019, at 10:54 AM, seantalts <notifications@github.com> wrote:
> 
> @bob-carpenter what do you think? It seems like in Stan there are a lot of places where we intentionally have choosen to make people choose different functions based on the types they're working with, even when the semantics are obvious.

For size, that was just an accident.  For append_row, append_col and append, that was intentional because you need to distinguish row from col appends.

> I think in some cases this is because the old type system was simple and bottom up - so we needed to know if someone was trying to build an vector vs an array with e.g. rep_vector vs rep_array.

That was also intentional.  And I think we should maintain the bottom-up nature of the type system and solve any polymorphism problems by extending the notion of assignment.  For example, I wouldn't want to conflate row vectors and vectors, but one could assign one to the other (I don't like this particular idea, just saying it'd be better with assignment than reducing the type distinction).

> In this case, size always returns an integer so it seems fine to extend its inputs if that's the only reason for those choices, but I'm not sure it was.

Yes, I think we should make size() general.  The question is really how to define it for something like an array of matrices.  Is it the size of the array, or the total size of all elements?  We need something for the size of just the array and a separate function for the total number of elements recursively.

**Comment by rok-cesnovar** [comment]
> It should even return 1 for scalars.

Yes, that is the plan.

```
template <typename T, typename = require_stan_scalar_t<T>>
inline size_t size(const T& /*x*/) {
  return 1U;
}

template <typename T, typename = require_not_stan_scalar_t<T>, typename = void>
inline size_t size(const T& m) {
  return m.size();
}
```

This would return the size of the array (matches what it does currently), size of a matrix and 1 for scalars.

**Comment by rok-cesnovar** [comment]
Great thanks to both of you for a quick response. Will get on this once the Math parts of it are merged.
