### ISSUE TITLE
MPI map_rect "unregistered class" exception

### ISSUE THREAD

**Issue by palderman** [stan-dev/stanc3#527]
When attempting to sample from the `logistic1.stan` model from [Multithreading and Map-Reduce in Stan 2.18.0: A Minimal Example](https://github.com/rmcelreath/cmdstan_map_rect_tutorial) using cmdstan and MPI I am getting an error:

```
Unrecoverable error evaluating the log probability at the initial value.
Exception: unregistered class - derived class not registered or exported (in 'cmdstan_map_rect_tutorial/logistic1.stan', line 39, column 2 to column 66) [origin: unknown original type]
Exception: unregistered class - derived class not registered or exported (in 'cmdstan_map_rect_tutorial/logistic1.stan', line 39, column 2 to column 66) [origin: unknown original type]
```
I have tried compiling with stanc2 and stanc3. In both cases, the model will compile without error, but the exception is thrown when trying to sample. The error is not present in code generated with stanc2. Comparison of the generated *.hpp files indicates that there is a line at the end of the stanc2-generated code ([logistic1_stanc2.txt](https://github.com/stan-dev/stanc3/files/4548500/logistic1_stanc2.txt)) that is missing in the stanc3-generated code ([logistic1_stanc3.txt](https://github.com/stan-dev/stanc3/files/4548501/logistic1_stanc3.txt)) that may be the source of the error:

```
STAN_REGISTER_MAP_RECT(1, logistic1_model_namespace::lp_reduce_functor__)
```

Further, if I paste the above line at the end of the stanc3-generated file, then the model runs fine.

**Comment by rok-cesnovar** [comment]
Hi, thanks for reporting.

This issue is the same as https://github.com/stan-dev/stanc3/issues/516.
I went and check that the proposed fix in https://github.com/stan-dev/stanc3/pull/517 fixes this issue as well.

Once the goes in, you can just delete the built stanc in your cmdstan and you will be able to work with stanc3. Until then you should use stanc2 for this model.

I am going to close this issue, given that it addresses the same thing as the one already open.
