### ISSUE TITLE
Indexed LValue bug

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#531]
#### Summary:
Currently, Stan treats LValues (left-hand-side of assignments) as having a flat indexing structure consisting of a single list of indices. This seems in contradiction with the treatment of RValues (right-hand-side of assignments).

#### Description:
For example: `a[:][2]` and `a[:, 2]` are equivalent as an LValue but not as an RValue.

#### Reproducible Steps:
Run 
```
model {
    int a[2, 2] = {{1, 2}, {3, 4}};
    a[:][2] = {17, 18};
    print(a);
}
```
and
```
model {
    int a[2, 2] = {{1, 2}, {3, 4}};
    a[:, 2] = {17, 18};
    print(a);
}
```
They give the same output.

Then run 
```
model {
    int a[2, 2] = {{1, 2}, {3, 4}};
    print(a[:][2]);
}
```
and
```
model {
    int a[2, 2] = {{1, 2}, {3, 4}};
    print(a[:, 2]);
}
```
They give different output.

#### Current Output:
Inconsistent behaviour between indexing in LValues and RValues.

#### Expected Output:
Consistency. I think the behaviour of RValues is the correct one.

#### Current Version:
v2.20.0

**Comment by bob-carpenter** [comment]
I thought this was already fixed, but I can't find a PR that matches.   This is a really serious bug and should be hotfixed ASAP if it hasn't already been fixed.  

This is a really serious bug because it'll break working stan2 programs in unexpected ways, and it'll lead to people writing code for the buggy behavior that'll break when we fix it.

Here's a recursive definition that reduces multi-index behavior to single-index behavior on both the LHS and RHS:

* `a [is, ...] [j, ...] = a [is[j]] [...] [...]` if `is` multi-index and `j` a single index

* `a [j, ...] = a [j] [...]` if `j` is a single index

The first bullt point defines the result of multi-indexing `a[idxs, ...]` by its action on single indexes. It follows that

* `a[is] [js] [k] = a[is] [js[k]] = a[is[js[k]]]`

**Comment by rok-cesnovar** [comment]
> This is a really serious bug because it'll break working stan2 programs in unexpected ways

This works the same way with stanc2 and stanc3.

Your example

```stan
parameters {
  real<lower = 0, upper = 1> theta;
}
model {
    int a[2, 2] = {{1, 2},
                   {3, 4}};
    print("a[2] = ", a[2]);
    print("a[ : ][2] = ", a[ : ][2]);
    print("a[ : , 2] = ", a[ : , 2]);
} 
```
outputs

```
a[2] = [3,4]
a[ : ][2] = [3,4]
a[ : , 2] = [2,4]
```
with cmdstan develop and develop + STANC2=true.

I am cleaning Stan issues (a few issues every day whenever I lose focus to do something more meaningful) and was not sure whether it is fixed or not.

**Comment by bob-carpenter** [comment]
I just confirmed that the example reported in the original issue is still broken.  This is a super critical bug in my opinion for compatibility reasons.  I think we should hotfix it ASAP if anyone can figure out how to do it.

Here's a reproducible example that's broken in the current cmdstan devlop branch:

```
transformed data {
  int a[2, 2] = {{1, 2}, {3, 4}};
  a[:][2] = {17, 18};
  print("");
  print("expect {{1, 2}, {17, 18}}");
  print(a);

  int b[2, 2] = {{1, 2}, {3, 4}};
  b[:, 2] = {17, 18};
  print("");
  print("expect {{1, 17}, {3, 18}}");
  print(b);

  int c[2, 2] = {{1, 2}, {3, 4}};
  print("");
  print("expect {3, 4}");
  print(c[:][2]);

  print("");
  print("expect {2, 4}");
  print(c[:, 2]);
}
```

The output is:

```
expect {{1, 2}, {17, 18}}
[[1,17],[3,18]]

expect {{1, 17}, {3, 18}}
[[1,17],[3,18]]

expect {3, 4}
[3,4]

expect {2, 4}
[2,4]
```

So the specific case that is broken is this one:

```
  int a[2, 2] = {{1, 2}, {3, 4}};
  a[:][2] = {17, 18};
```

It should evaluate `a[:]` to be equal to `a`, so that `a[:][2] is the second row of the matrix, so that setting it should yield `{{1, 2}, {17, 18}}`.  Instead, it sets the second column and returns ``{{1, 17}, {3, 18}}`, which is wrong.

**Comment by rok-cesnovar** [comment]
Is this different to what was going on in stanc2?

From my tests I saw no difference.

**Comment by nhuurre** [comment]
I disagree that this is critical. It has never worked the intended way, not even in stanc2. If anyone has ever relied on this they must expect the buggy behavior by now. In my opinion we should "fix" this by disallowing lvalue nested indexing.

**Comment by bob-carpenter** [comment]
@nhuurre is right---I verified this is is broken in stanc, too.  So now I also agree with @nhuurre's mitigation plan.  Specifically, I now think we should

1.  add documentation around how lvalues work in the reference manual, and 

2.  deprecate the use of multiple bracketed indexes on lvalues for now, eventually eliminating them when we properly move to Stan 3 across the board and remove all the old deprecated features.
