### ISSUE TITLE
promote int to real, double-based divide function

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stanc3#533]
#### to_real()

Add a special function:

```
real to_real(int);
```
- [ ] code
- [ ] tests
- [ ] doc in manual

Suggested implementation:

```
double to_real(int x) { return x; }
```

Would this clearer with a static cast?
#### div()

Add a special function

```
real div(real,real);
```
- [ ] code
- [ ] tests
- [ ] doc in manual

Suggested implementation:

```
double div(double x, double y) { return x / y; }
```
#### Motivation

The motivation is that I'm implementing some mark-recapture models that involve integer populations, but I need a fractional bound on a real parameter that's currently cumbersome to write:

```
data {
  int<lower=0> M;                       // marked
  int<lower=0> C;                       // captured
  int<lower=0,upper=min(M,C)> R;        // recaptured
}
transformed data { // HACK!
  real theta_max;     
  theta_max <- M;         
  theta_max <- theta_max / (C - R + M);
}
parameters {
  real<lower=0,upper=theta_max> theta;  // proportion marked
}
...
```

I would prefer to get rid of the transformed data division hack and just write:

```
parameters {
  real<lower=0,upper=div(M, C - R + M)> theta;  // proportion marked
}
```

Without the constraint, you get inconsistent values of theta that are above the upper bound.

**Comment by nhuurre** [comment]
`to_real` is not necessary since you can always multiply by `1.0`. And as far as I know division is the only place where the compiler doesn't autoconvert ints to reals.

The int division problem came up on [the forum a few months ago](https://discourse.mc-stan.org/t/proposal-explicit-integer-division/14043). Does anyone object to my proposal for integer division operator?
```stan
int a;
int b;
int c = a %/ b; // integer division, rounds down
real d = a / b; // real division, no rounding
```

**Comment by martinmodrak** [comment]
If integer division is added as a new operator, I think we should try to follow at least one other language and not invent our own, although most languages I've seen have named functions for integer (floor) division.  

I've tried to do a survey of integer division operators in use:

- `//` in Python (we can't have this as it is start of comment in Stan)
- `%/%` in [R](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Arithmetic.html) - I like this because many Stan users use R (although few would be actually familiar with this operator)
- `\` used in [Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/integer-division-operator) as well as Access and other MS products. Also in [ColdFusion](https://www.bennadel.com/blog/2031-the-integer-division-operator-in-coldfusion.htm).
- `÷` used in [Julia](https://docs.julialang.org/en/v1/manual/mathematical-operations/) - although I think you can't write this on most keyboards...
- `div` used in [Pascal](https://wiki.freepascal.org/Div) (this might cause some name conflicts)

I agree with @bob-carpenter that `int / int` needs to stay, but it should IMHO provide a warning with suggestion to either use `to_real` or integer division.

**Comment by nhuurre** [comment]
`int / int` emits a warning right now and is going to round for at least a few releases. Users who want fractions have to use "the real division operator" `*1.0/`.
Changing the return type is breaking but often not silent; int division is mostly useful for calculating indices and there an unexpected `real` causes a type error.

The question is what to call the int division operator. @martinmodrak's survey has only one good option.
* Python's `//` is my personal favorite but of course it's not available. (thanks, C++)
* R's `%/%`: I'd prefer the shorter `%/` but this is fine too.
* Visual Basic `\`: Nope, `\` is already a Stan operator, it means matrix left-division.
* Julia `÷`: The parser does not allow non-ascii characters outside of comments.
* Pascal `div`: A keyword that is an infix operator? Please no.

**Comment by bob-carpenter** [comment]
So which is the good option?  Wasn't @nhuurre's original proposal to overload `./` to scalar types?  If we do that, it makes sense to cast to real since it's underlyingly a vector operation and vectors are all real.  I don't think any of these (including just leaving things the way they are) make it clear to a reader of a program what's going on.  

To undertand int / int is an int, they need to know that Stan works like C++ and Java, not like R.  To understand what `div` or `%/%` or `./` means, they need to read our doc.

Also, we already use `\` for left matrix division.
