### ISSUE TITLE
Expose functions suite for hmm

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/stanc3#535]
This complements issues stan-dev/math#1648 and stan-dev/math#1846. Expose the signature for the following three functions:

* `hmm_marginal()`
* `hmm_hidden_state_prob()`
* `hmm_latent_rng()`

**EDIT:** updated signatures per discussion.

**Comment by charlesm93** [comment]
As I started writing the function signature for hmm_marginal_lpdf, I realized the function didn't have the format
```
  target += hmm_marginal_lpdf(y | ...);
```

The signature is
```
target += hmm_marginal_lpdf(log_omega, Gamma, rho);
```
and the data is implicitly passed through `log_omega`, which may in turn depend on model parameters. Naturally something of the form
```
log_omega ~ hmm_marginal_lpdf(Gamma, rho);
```
wouldn't make sense. 

The solution to this problem is to only allow a call to the function via `target +=` but this might preclude using the suffix lpdf.

@bob-carpenter, @betanalpha

**Comment by charlesm93** [comment]
Note: when editing `stan_math_signaturs.ml` and adding an element to distributions, the code also generates an rng function, `real[] hmm_marginal_rng` but such a function is not defined. The workaround, it seems, would be to directly expose the function signature using `add_qualified`. But this doesn't give us the `log_omega ~ hmm_marginal(Gamma, rho);` option for free.

**Comment by bob-carpenter** [comment]
I'm getting lost with the diffs.  Can you edit the issue to include the proposed signatures for these functions?  

If there's a function `foo_lpdf(y, ...)`, then it should be automically callable as `y ~ foo(...)`.  

The doc needs to be careful in explaining that this is an lpdf that can also act as an lpmf because `y` might be an integral type.  I'd be worried that general type checking disallow an integral LHS `y` for an lpdf.

**Comment by nhuurre** [comment]
When we discussed the name I thought the observed states were going to be discrete and explicitly part of the signature but I now see this is written in more general form and what I was thinking is simply
```stan
target += hmm_marginal_lpdf(log_omega[:,y], Gamma, rho);
```

If the observed state is not part of the signature then it's not a lpdf/lpmf function; it's an analog of `log_mix`. The function name should be `log_marginalize_hmm`, not anything with `_lpdf`.

**Comment by betanalpha** [comment]
> If there's a function foo_lpdf(y, ...), then it should be automically callable as y ~ foo(...).
> 
> The doc needs to be careful in explaining that this is an lpdf that can also act as an lpmf because y might be an integral type. I'd be worried that general type checking disallow an integral LHS y for an lpdf.
> 
The problem here is that the current convention for “_lpdf” in the Stan language 
is somewhat awkwardly defined.  

Right now all of our “_lpdf" functions define _conditional_ probability density 
functions over one-dimensional spaces, hence always having a bar in the 
signature separating the unbound/unconditioned variable that parameterizes 
the unconditioned component space and the bound/conditioned variables that 
parameterize the conditioning component spaces.

The ~ is slightly less restrictive, being well-defined for variables that directly 
parameterize a component space but not requiring any conditioning.

The “hmm_marginal” function returns a log probability density, but it is not a 
conditional probability density function in the traditional sense since it is not
directly parameterized by a variable that itself coordinates the unconditioned 
component space but rather an intermediate computation.  

The confusion around lpdf and lpmf also arises from the somewhat ambiguous 
conventions that we defined early on.  Technically both real-valued probability 
density functions and integer-valued probability mass functions are density 
functions, just with respect to different reference measures.  In other words 
“density function” is overloaded to include both the general and the real case 
so there’s no natural alternative for described mixed density functions (unless
we want to add “lrnd” for “log Radon-Nikodym derivative” and really confuse
people.

If we maintain the current, technically arbitrary, lpdf and lpmf conventions then 
we would need a new name that generalizes to mixed inputs and functions 
that return densities but don’t directly input parameters of the ambient space.  
There aren’t any common terms for these, so we would have to make something 
up to provide the desired differentiation.

If we want to redefine the conventions for lpdf to include both real and mixed
and not necessarily conditional or inputting parameters of the ambient space 
then we can stick with “hmm_marginal_lpdf”.

**Comment by bob-carpenter** [comment]
I was confusing the two "marginal" functions.  If z is the sequence of latent states and y the sequence of observations, then

1.  The data marginal p(y | theta) can be either discrete or continuous, because y can be either discrete or continuous.  This is the one where `_lpdf` is confusing because it can act like an `_lpmf`.

2.  The latent state marginal p(z | y, theta) conditioned on data y is definitely discrete. But that's not what's being implemented here.  Rather the sequence of marginals p(z[n] | theta) are being computed.  So I agree this shouldn't be an `_lpmf` function. 

The naming is confusing here because p(z | theta) is the actual Markov model and that's also a kind of marginal if you're thinking of (y, z) as the complete data in the frequentist sense.  That marginal would make sense to implement as an `_lpmf`.  And that's the one that I said I don't see anyone ever implement in their HMM packages.  I was thinking that's what was going to be implemented rather than what I think of as the forward-backward algorithm to compute the latent state marginals conditional on data, p(z[1] | y, theta), ..., p(z[N] | y, theta).  The other sensible latent conditional marginal would be just p(z | y, theta).  That's a marginal distribution over the sequence p(z[1], ..., z[N] | theta) rather than a sequence of marginal distributions p(z[1] | theta), ..., p(z[N] | theta).

**Comment by betanalpha** [comment]
To be clear the current code implicitly implements

log(pi( y | theta, phi))

through a function that takes in the evaluated observational densities,

f( log(pi(y | phi)), theta) = log(pi(y | theta, phi)).

It returns a log probability density but it does not take as input a 
parameterization of the ambient space, so isn’t a complete Radon-Nikodym 
derivative and hence a complete, classically-defined probability density 
function.

To reiterate “_lpdf” referring to only real-valued probability density functions 
is a Stan convention; in the prob/stats literature it is overloaded to refer
to both general or mixed density functions and the real-valued density 
functions.  If we don’t want to follow that overloaded convention and instead
stick to the current Stan convention then we have to come up with another,
arbitrary, name for the more general setting.

**Comment by bob-carpenter** [comment]
Thanks for summarizing @betanalpha.  Although it wasn't my first choice, I'm OK with 

* `hmm_marginal_lpdf(y | ...)` for `log p(y | ...)`

where `y` is observed sequence and `...` is the parameter sequence.

I'm not so sure about

* `hmm_latent_marginal_prob` for `log p(z[1] | y, ...), ..., log p(z[N] | y, ...)`.

It's confusing in conjunction with `hmm_marginal_lpdf` because (a) it's not only marginal, it's conditioned on data, and (b) it's a sequence of marginal probabilities, not a single marginal.

**Comment by betanalpha** [comment]
> Thanks for summarizing @betanalpha <https://github.com/betanalpha>. Although it wasn't my first choice, I'm OK with
> 
> hmm_marginal_lpdf(y | ...) for log p(y | ...)
> where y is observed sequence and ... is the parameter sequence
> 
To clarify that is not one of the functions being implemented — it would 
require fixing an observational model which we do not do.  Instead 
we take in the parameters and a sequence of log observational densities
to return the log pi(y | theta) that results from the implicitly specified 
observational model.

> I'm not so sure about
> 
> hmm_latent_marginal_prob for log p(z[1] | y, ...), ..., log p(z[N] | y, ...).
> It's confusing in conjunction with hmm_marginal_lpdf because (a) it's not only marginal, it's conditioned on data, and (b) it's a sequence of marginal probabilities, not a single marginal.
> 
“latent” here refers to the hidden states, as in “marginal probability
for the hidden states at each iteration” so there isn’t an ambiguity.
I used “hidden_states” in the original prototype — Charles why did 
you prefer “latent”?

Regarding whether or not “marginal” is the right word I have no 
problem going with “hmm_hidden_state_cond_probs” or something.

**Comment by charlesm93** [comment]
It looks like the function at hand is not an lpdf in the Stan sense of the word. I'm not familiar with `log mix`, but I think @nhuurre has the right idea: we should not use the suffix `lpdf`. Per @betanalpha we can add a new suffix. I propose the general term `target`. The function is then used as
```
target += hmm_marginal_taget(log_omegas, Gamma, rho);
```

Regarding the name `hmm_latent_marginal_prob`, I'm ok tochanging it. Would
```
hmm_hidden_state_prob
```
do? The cond is ambiguous, because there are many things we can condition on. The reason I included marginal is because of my own initial confusion; I thought the term could be used to generate latent states, but @betanalpha pointed out we couldn't do this because we only had the marginal probabilities. So I added the term marginal. But I don't mind removing it.

**Comment by bob-carpenter** [comment]
I think it's OK to use it without a suffix.  So that's just `hmm_marginal`.  I don't think `target` adds anything.  We don't add `_target` to `log_mix` or `log_sum_exp` even though we use those a lot on the right hand side of a `target +=` statement.

Is it a prob or log prob for the hidden states, right?  Working on the linear scale has some risk of underflow, but that's already cooked into the algorithm.  I still like simpler, so something like `hmm_hidden`.  I also think of these as marginals.  It is `p(z[i] | y, theta)`, isn't it, for each `i` separately (where `z[i]` is the hidden state and `y` the observation sequence and `theta` all the params).

**Comment by betanalpha** [comment]
> Is it a prob or log prob for the hidden states, right? Working on the linear scale has some risk of underflow, but that's already cooked into the algorithm. I still like simpler, so something like hmm_hidden. I also think of these as marginals. It is p(z[i] | y, theta), isn't it, for each i separately (where z[i] is the hidden state and y the observation sequence and theta all the params).

Right, so the confusion is that these (linear) probabilities are both marginal, 
for the hidden states at each iteration, _and_ conditional, on the observations 
and the global parameters.  Trying to denote this in the function name is 
only going to lead to a Chinatown-style back and forth so I agree that it’s 
best to avoid it entirely.  I personally prefer Charles’ suggestion of 
`hmm_hidden_state_prob`. 

I’m also find with `hmm_marginal` for the incomplete density function, 
although it would be good to come up with a consistent name for functions 
that consume probability densities and return transformed probability densities 
but are themselves not Radon-Nikodym derivatives, even if just for the
documentation and not the language.

**Comment by charlesm93** [comment]
I'll edit the `math` branch and change the name of functions to have `hmm_marginal` and `hmm_hidden_state_prob`.

**Comment by charlesm93** [comment]
`hmm_hidden_state_prob` is not differentiable. Questions: (i) do we want to make it differentiable (please, only if there is a specific application, it's quite a bit of work!), (ii) if it's not differentiable, how do I restrict its call to the generated quantities block?

**Comment by nhuurre** [comment]
`add_qualified` can create signatures that are only partially autodiffable. It's used for example to declare `integrate_ode_*` functions with data-only restrictions on some arguments.

If `hmm_hidden_state_prob()` is not differentiable at all the signature is
```ocaml
  add_qualified
    ( "hmm_hidden_state_prob"
    , ReturnType UReal
    , [(DataOnly, UMatrix); (DataOnly, UMatrix); (DataOnly, UVector)] ) ;
```
or whatever the parameter types are.

**Comment by bob-carpenter** [comment]
> Questions: (i) do we want to make it differentiable (please, only if there is a specific application, it's quite a bit of work!),

Is it more work than just appropriately templating the prim definition?  If not, then maybe you can call in more help on this one as it's the same kind of job as making things work for fvar---all the intermediates just have to be the right type.  And that's a whole lot easier now with `auto`.

**Comment by charlesm93** [comment]
@nhuurre The input can still depend on parameters (much like an rng function). What we'd want is for the log joint density to not depend on the output.

@bob-carpenter I suppose it's fine if we brute-force the derivatives. I do find it to be a pain to deal with fvar and co, and to not use Eigen's operation. Especially if there are no obvious use cases. That said, since in the applications I forsee we'll use this mainly in the rng block, performance is not too large of a concern.

But let me reiterate: what are the use cases?

**Comment by nhuurre** [comment]
Ah, ok. It's not possible to enforce that kind of invariant. Rng functions are special-cased in `Semantic_check.ml`.

**Comment by bob-carpenter** [comment]
Can I go back and ask what the use cases are for this function full stop?  Is there an example usage somewhere?

We may also want  to want to implement the standard Viterbi algorithm for first-best decoding which will have the same issues.  I coded it in Stan, which leads to a less efficient but fully differentiable implementation.  It may be in the user's guide chapter.

My main motivation for the fnction being differentiable is to not add yet another kind of function that needs special doc and special handling in the parser.   It's a kind of technical debt I'd rather not have unless we absolutely need it.  I'm not sure how the hassle of  generalizing the function compares to hassle of adding a new type of function to the parser and doc.

**Comment by bob-carpenter** [comment]
Also, in generated quantities, every argument is `data` because it's all `double` based, even the parameters.  So if the restriction is to generated quantities and transformed data, it might be enough just to mark all the arguments as `data`.  

Will that be easy in the stanc3 parser?   If it's done in general there, we shouldn't need to change much code or doc to handle it.

**Comment by betanalpha** [comment]
The intended use case of this function is entirely be in the generated quantities block.
It’s not quite an RNG but it basically serves the same purpose — generating values 
conditioned on the current values of the parameters but not otherwise affecting the model.

This pattern isn’t unique but also not quite common yet in Stan.  It shows up anytime 
one uses a marginal density to implement a model but wants to investigate/analyze the
parameters that were marginalized out.

Trying to force differentiability introduces its own mound of technical debt — the code gets
much nastier and harder to maintain while also allowing users to misuse the function in
potentially dangerous ways.

**Comment by charlesm93** [comment]
> Will that be easy in the stanc3 parser?

Yes, it's super easy to specify data only arguments! See the example code @nhuurre produced.

**Comment by bob-carpenter** [comment]
I'm OK with this if it'll work with `data` qualifiers on the arguments.

**Comment by nhuurre** [comment]
> if the restriction is to generated quantities and transformed data, it might be enough just to mark all the arguments as data.

Yes, that's how it should work but stanc3 (and stanc2) is buggy. I opened a new issue #540

**Comment by charlesm93** [comment]
I tried using data only (first for one of the arguments),
```
add_unqualified
    ("hmm_hidden_state_prob", ReturnType UMatrix, [UMatrix; UMatrix; (DataOnly, UVector)]) ;
```
and get the following error message
```
File "src/middle/Stan_math_signatures.ml", line 949, characters 69-88:
Error: This expression has type 'a * 'b
       but an expression was expected of type UnsizedType.t
```
I've definitely used `DataOnly` in the past. I'll keep tinkering.

**Comment by rok-cesnovar** [comment]
You need to use add_qualified:


```ocaml
  add_qualified
    ("hmm_hidden_state_prob", ReturnType UMatrix, [(AutoDiffable, UMatrix); (AutoDiffable, UMatrix); (DataOnly, UVector)]) ;
```

**Comment by charlesm93** [comment]
yup, was just trying that. Now I get the distinction between qualified / unqualified

**Comment by charlesm93** [comment]
Unfortunately, the above prescribed signature prevents us from passing parameter arguments, even in the generated quantities block. From the `hmm_hidden_state_prob.stan` file, when running the tests, I get the following error:
```
+Ill-typed arguments supplied to function 'hmm_hidden_state_prob'. Available signatures: 
+(data matrix, data matrix, data vector) => matrix
+Instead supplied arguments of incompatible type: matrix, matrix, vector.
```
which is caused by the first argument being a parameter. I reckon we could put a restriction on this function, as we do on rng functions, though I'm not quite sure where would be the best place to try this.

**Comment by rok-cesnovar** [comment]
This is due to https://github.com/stan-dev/stanc3/issues/540

@nhuurre do you have a hunch on how to fix this one?

**Comment by rok-cesnovar** [comment]
The restriction for _rngs are done here: https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_check.ml#L264

**Comment by rok-cesnovar** [comment]
@charlesm93 the generated quantities issue with parameters and data only arguments was merged. So the above issue should be gone.

**Comment by charlesm93** [comment]
I built all the relevant models that need to be tested. However,  when typing
```
dune runtest test/integration
```
it doesn't look like the bad models get checked (` test/integration/bad/hmm_hidden_state_prob/`). The files don't get build (i.e. they don't appear under `_build/`). Is there something that needs to be done for these files to be built?

**Comment by rok-cesnovar** [comment]
You are missing the dune file in the folder. That specifies how to run tests. See https://github.com/stan-dev/stanc3/tree/feature/issue-535-hmm/test/integration/bad/algebra_solver

It suffices to just do what is done in this folder's dune file that basically says: use rule from parent.

**Comment by charlesm93** [comment]
Thanks. I still had to create a `stanc.expected` inside `hmm_hidden_state_prob` but things seem to work. I'll submit the PR once all the math functions are merged.
