### ISSUE TITLE
Unnormalized densities with reduce_sum

### ISSUE THREAD

**Issue by wds15** [stan-dev/stanc3#541]
Right now we can only have user defined densities given to reduce_sum which use normalized densities. Often the normalization is not needed and does cost unneccessary performance (for example the poisson_lpmf).

So right now it‘s only possible to use things like 

`lp += poisson_log_lpmf(y | mu)`

Within functions passed to reduce_sum. It should be possible to use the equivalent of

`y ~ poisson_log(mu)`

Inside functions passed to reduce_su. This is a lot faster and gives the same inference.

**Comment by rok-cesnovar** [comment]
This is waiting for https://github.com/stan-dev/stanc3/issues/253. We should fix that for the next release and document it in the docs repo.

**Comment by rok-cesnovar** [comment]
We don't have to add anything else for reduce_sum specifically once that is fixed.

**Comment by wds15** [comment]
I hope that‘s easy to get done... and yeah it‘s probably not reduce_sum specific.

**Comment by rok-cesnovar** [comment]
I think the "get done" should not be that hard as it should, in theory, be a rename from the undocumented
```
lp += poisson_log_propto_lpmf(y | mu)
```
to
```
lp += poisson_log_lupmf(y | mu)
```

**Comment by nhuurre** [comment]
Back when this first came up on Discourse I said `propto` infix didn't do anything inside user-defined functions. I double-checked and turns out I was wrong. Unnormalized densities _can_ be used in `reduce_sum` functions right now.
However, I think `propto` should not be allowed outside of model block and `_lpdf` functions. Otherwise we get rather surprising results:
```stan
functions {
  real lprob(real x) {
    return normal_propto_lpdf(x | 0, 1);
  }
}
parameters {
  real x;
}
transformed parameters {
  real ll = lprob(x);
}
model {
  target += ll;
}
```
You'd think `ll` is equal to `target`/`lp__` but no; the output says `ll` is always zero.

**Comment by bob-carpenter** [comment]
The sampling statement syntax is that it's only valid in the model block.  

I didn't undersand the problem from @nhuurre's comment.  I don't think `ll` would be zero because `x` is a parameter and hence not data.  But it will be an issue in transformed data or generated quantities, where all arguments are always data and hence all propto evaluations are zero.

**Comment by nhuurre** [comment]
Sampling syntax is also allowed inside functions with `_lp` suffix. Which suggest maybe we want `reduce_sum_lp`...

Thanks, @bob-carpenter , for confirming that the problem is confusing even for someone with deep understanding of Stan's internals.

When I run the above model the result is
```
                 Mean     MCSE   StdDev     5%       50%       95%    N_Eff  N_Eff/s    R_hat
lp__            -0.52  3.4e-02  7.3e-01   -2.1  -2.2e-01  -2.7e-03  4.7e+02  1.0e+04  1.0e+00
accept_stat__    0.92  3.5e-03  1.1e-01   0.68   9.7e-01   1.0e+00  1.0e+03  2.2e+04  1.0e+00
stepsize__        1.1      nan  2.2e-15    1.1   1.1e+00   1.1e+00      nan      nan      nan
treedepth__       1.3  1.6e-02  4.7e-01    1.0   1.0e+00   2.0e+00  9.1e+02  2.0e+04  1.0e+00
n_leapfrog__      2.3  3.6e-02  9.4e-01    1.0   3.0e+00   3.0e+00  6.7e+02  1.4e+04  1.0e+00
divergent__      0.00      nan  0.0e+00   0.00   0.0e+00   0.0e+00      nan      nan      nan
energy__          1.0  4.6e-02  9.9e-01  0.053   6.6e-01   3.1e+00  4.7e+02  1.0e+04  1.0e+00
x               0.015  6.2e-02  1.0e+00   -1.7  -1.7e-02   1.8e+00  2.7e+02  5.7e+03  1.0e+00
ll               0.00      nan  0.0e+00   0.00   0.0e+00   0.0e+00      nan      nan      nan
```
And that obviously doesn't make a whole lot of sense. `ll` shouldn't be zero and if it is then how can `lp__` be nonzero?
Well, transformed parameters block is executed twice. First when the sampler calls the model's `log_prob()` and there indeed `x` is autodiffable and `ll` has value equal to `target`. But `log_prob` _returns only one value_, the `target`. Transformed parameters are not saved!
The second time happens when the sampler has chosen which sample to save and calls `write_array()`. The method reconstructs the transformed parameters by running the code again _but this time everything is double_. These are the values that get saved in the output.
