### ISSUE TITLE
Eliminate structs that wrap user-defined functions

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stanc3#583]
#### Summary:

The parser should not generate structs that call user-defined functions anymore. We should use generalized lambda functions instead.

#### Description:

A user-defined function `foo` will generate additional C++ that looks something like
```
struct foo_functor__ {
    templates
    return_type
    operator()(..., std::ostream* pstream__) const {
        return foo(..., pstream__);
    }
};
```
irrespective of whether `foo_functor__` actually gets called by one of the functionals. The parser should not generate `foo_functor__`, and if functionals are used in the Stan program, then `stanc` should utilize a generalized lambda function that calls `foo`.

This would also allow us to avoid the unnecessary restriction that you cannot define multiple user-defined functions with the same name (but different signatures). See

https://github.com/stan-dev/stan/issues/1547

#### Reproducible Steps:

Parse
```
functions {
  void foo() {
  
  }
}
```

and look at the C++ code

#### Current Output:

```
struct foo_functor__ {
            void
    operator()(std::ostream* pstream__) const {
        return foo(pstream__);
    }
};
```

#### Expected Output:

Not that part

#### Additional Information:

None

#### Current Version:
v2.18.0

**Comment by WardBrian** [comment]
I realize this is a relatively old issue, but I'm taking a look at function overloading now and it seems relevant to that still. I believe since this issue was first created, moving away from these functors has gotten much more difficult. In particular, `map_rect` and `reduce_sum` both take the function they handle as a type in a template parameter, rather than the actually instantiated functor. 

It seems to me like those are probably best left as functors. The rest seem like they're candidates for generalized lambdas. There is then a question about whether or not it makes sense to allow overloaded functions as arguments to `reduce_sum` (`map_rect` only accepts one signature, so the answer is trivially "no" for that function). If we want to allow that, then generating functors requires some sort of pooling of all the existing signatures into one struct with multiple `operator()` definitions.

And, if we're pooling all definitions of a function into one functor with multiple `operator()` definitions, then that would be sufficient for overloading to begin with, without the need to change anything else to a generalized lambda.

**Comment by WardBrian** [comment]
I think the way that overloading (#1027) handled this and the requirements of map_rect and reduce_sum are enough to close this issue
