### ISSUE TITLE
Deprecation warnings are missing for functions

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/stanc3#600]
This model:

```
model {
  real foo;
  foo = multiply_log(1, 1);
}
```
issue a warning with STANC2:
```
DIAGNOSTIC(S) FROM PARSER:
Info: Function name 'multiply_log' is deprecated and will be removed in a later release; please replace with 'lmultiply'
```

but nothing with stanc3. 

stanc3 does handle some deprecation warnings for the uses of #, <-, increment_log_prob and get_lp.

We use a list of deprecated functions in the canonicalizer: https://github.com/stan-dev/stanc3/blob/master/src/frontend/Canonicalize.ml#L8

That list should be moved out of the canonicalizer mode and warn in regular use and replace in canonicalizer.
Also warn for the _log suffix, _log UDFs, add cov_exp_quad to the deprecated list in favor of gp_cov_exp_quad. There might be others.

Reference manual list of deprecated features: https://github.com/stan-dev/docs/blob/068bda7038671e89fb4574d2cc56a3f6e351d01f/src/reference-manual/deprecations.Rmd

**Comment by adamhaber** [comment]
Hi,

> Reference manual list of deprecated features: 

Some followup questions:
1. "Replace `lkj_cov_log(...)` with an `lkj_corr` distribution on the correlation matrix and independent lognormal distributions on the scales. " - should this be included? 
2. `if_else` replaced with `a ? b : c` - presumably should be handled but not included in the list, since it's not a simple-replace-this-function-with-this-function? 
3. "Use of the `abs` function with real-valued arguments is deprecated; use functions `fabs` instead." - same question.

> That list should be moved out of the canonicalizer mode and warn in regular use and replace in canonicalizer.

Moved the list to ast.ml (not sure it's the best place). Do we want to repeat all the canonicalizer `replace_deprecated_X` with `warn_deprecated_X` in ast (or a better location)?

**Comment by rok-cesnovar** [comment]
Hey,

for 1. I am not the best one to say (maybe @bob-carpenter , @bbbales2 )?

I am not sure why the canonicalizer doesn't handle 2 and 3. @nhuurre I guess 2 is not easy, any specific reason for 3? 
I personally think we should warn for both.

> Do we want to repeat all the canonicalizer `replace_deprecated_X` with `warn_deprecated_X` in ast (or a better location)

I think so yes. The location seems fine to me.

**Comment by nhuurre** [comment]
1. The canonicalizer does not fix `lkj_cov_log` because there's no simple substitution. Stanc2's deprecation warning suggest reparametrizing the model.
2. It does replace `if_else` with `?:`. It's not function-to-function substitution so it's not included in the list of deprecated functions.
3. The situation with `fabs` vs `abs` has changed. See issue #457

Note that the lexer already issues a deprecation warning for `ArrowAssign`, `GetLP`, and `IncrementLogProb`

https://github.com/stan-dev/stanc3/blob/c81db71084d935d1d1f4ca4da8644c7d2003b04c/src/frontend/lexer.mll#L159-L166

The lexer might not be the best place to handle that.

A big part of this issue is to figure out where and when to do the printing. The pretty printer silences the lexer warnings but the int division warning in semantic check prints unconditionally which is a problem because it's appended to the output file.

**Comment by nhuurre** [comment]
Sorry, `fabs/abs` issue is #475

**Comment by rok-cesnovar** [comment]
We will also need this for the ode interface after #525

**Comment by rok-cesnovar** [comment]
> The pretty printer silences the lexer warnings but the int division warning in semantic check prints unconditionally which is a problem because it's appended to the output file.

Can you elaborate on this a bit. To what output file is this appended? Do you mean the cpp file? I did not see any problems trying out the operator.

**Comment by nhuurre** [comment]
I mean the output of --auto-format or --print-canonical.
TFP backend has the same problem of piping everything to the standard output stream. Try and compile any Stan model with int / int to TFP and see if the .py file runs.

**Comment by adamhaber** [comment]
> A big part of this issue is to figure out where and when to do the printing.

1. Where to put this - would Fronend_utils be a reasonable place? Or perhaps in a separate Deprecation_analsis file?
2. When to do the printing - inserting a stage between ast and typed_ast in stanc/stancjs?

**Comment by adamhaber** [comment]
@nhuurre @rok-cesnovar what do think?

**Comment by adamhaber** [comment]
@nhuurre @rok-cesnovar is this still relevant? Not urgent, just bumping so we can proceed/close.

**Comment by rok-cesnovar** [comment]
Hi, yes this is still relevant. Sorry I missed this.

> * Where to put this - would Fronend_utils be a reasonable place? Or perhaps in a separate Deprecation_analysis file?

I think any of those are fine. I would maybe lean towards separate file, but no strong opinion here.


> 2\. When to do the printing - inserting a stage between ast and typed_ast in stanc/stancjs?

I would say yes.

**Comment by adamhaber** [comment]
No problem. Several questions regarding implementation:
1.  AFAIU, we want to completely decouple the deprecation warnings pass (which should be called by default) and the canonicalizer fixing-stuff pass; would it make sense to add a "replace/warn" boolean flag to the current functions (`replace_deprecated_stmt` and everything downstream) to avoid all the code duplication?  
2. The canonicalizer current has `repair_syntax` function which is never used - can it be removed?
3. We want deprecation warnings for pretty much anything that's currently a replacement in `replace_deprecated_expr`, not necessarily function renaming, right? Asking because
> Also warn for the _log suffix, _log UDFs,

**Comment by rok-cesnovar** [comment]
> 1. would it make sense to add a "replace/warn" boolean flag to the current functions (`replace_deprecated_stmt` and everything downstream) to avoid all the code duplication

I think that makes sense.

> 2\. The canonicalizer current has `repair_syntax` function which is never used - can it be removed?

I am not sure so I will defer this one to @nhuurre 

> 3\. We want deprecation warnings for pretty much anything that's currently a replacement in `replace_deprecated_expr`, not necessarily function renaming, right?

That is correct yes.

**Comment by nhuurre** [comment]
The `repair_syntax` function is used here
https://github.com/stan-dev/stanc3/blob/07046cfe8baa4499a6b09e6e98adfb3d2f229cbb/src/stanc/stanc.ml#L158-L160
It's separate from the `canonicalize_program` because it must change the AST _before_ type-checking.
However, `repair_syntax_expr` function is obsolete, it was just a workaround for issue #393 which has been fixed since.
The `repair_syntax_stmt` is required, as discussed in [the canonicalizer PR](https://github.com/stan-dev/stanc3/pull/390#issuecomment-557284006).

**Comment by adamhaber** [comment]
> The repair_syntax function is used here

Missed this, thanks for the clarification.

> However, repair_syntax_expr function is obsolete, it was just a workaround for issue #393 which has been fixed since.
The repair_syntax_stmt is required, as discussed in the canonicalizer PR.

Just to make sure I'm not missing anything - if `repair_syntax_expr` is obsolete (and can be removed), than so is `repair_syntax_lval` and therefore the only thing `repair_syntax_stmt` does is here
https://github.com/stan-dev/stanc3/blob/e5097e529cad72efd186edd586c7cad9f812d0ed/src/frontend/Canonicalize.ml#L84
right?

**Comment by nhuurre** [comment]
Yes, that's right.

**Comment by adamhaber** [comment]
One question (probably not directly related to this issue): I've added a the following function to Deprecation_analysis.ml:
```ocaml
let warn_deprecated (loc_span, message) =
  Fmt.pf Fmt.stderr 
    "@[<v>@,Warning: deprecated language construct used in %s:@,%s@]@."
    (Location_span.to_string loc_span) message
```
When I `dune runtest`, roughly around test 4100 it gets stuck. Specifically, AFAIU, the tests that involve run_bin_on_args get stuck. If I change `Fmt.stderr` to `Fmt.stdout` I don't have this problem. Any idea how to solve this?

**Comment by rok-cesnovar** [comment]
Maybe this is the same bug that is mentioned in this comment: https://github.com/stan-dev/stanc3/blob/master/src/analysis_and_optimization/Pedantic_analysis.ml#L312

Maybe @rybern would know more.

**Comment by adamhaber** [comment]
Definitely seems related; I've tried 
```ocaml
let warn_deprecated (loc_span, message) =
  Out_channel.output_string Out_channel.stderr (Fmt.strf 
                                                  "@[<v>@,Warning: deprecated language construct used in %s:@,%s@]@."
                                                  (Location_span.to_string loc_span) message)
```
but still got the same bug.

**Comment by seantalts** [comment]
Do you have the code up somewhere I can play around with it?

**Comment by adamhaber** [comment]
Sure, [here's](https://github.com/adamhaber/stanc3/blob/add-function-deprectation-warning/src/frontend/Deprecation_analysis.ml) the new Deprecation_analysis module. Other than that, Canonicalize.ml is changed (many of the shared functions were moved to Deprecation_analysis), and in stanc.ml:
```ocaml
  let typed_ast =
    Deprecation_analysis.emit_warnings (Frontend_utils.type_ast_or_exit ast)
  in
```
Any feedback would be much appreciated, thanks!

**Comment by adamhaber** [comment]
@seantalts @rok-cesnovar any ideas? This currently prevents me from finishing this, but I was not able to find a workaround...

**Comment by rok-cesnovar** [comment]
I am guessing stderr gets flooded, primarily because of https://github.com/stan-dev/stanc3/tree/master/test/integration/good/function-signatures/distributions/univariate/continuous

Those test models mostly still use the deprecated `_log` suffixes. https://github.com/stan-dev/stanc3/tree/master/test/integration/good/function-signatures/distributions/univariate/continuous/wiener has 100k+ calls to wiener_log for example. So that means 100k deprecation warnings.

I cant confirm this 100%, but if I modify the code so that there are no `_log` warnings, `dune runtest` works.

I don't think brute-forcing this test somehow and having a million deprecation warnings for these test models is the way we want to go. I see no reason why we should have the function-signatures for distributions in the deprecated `_log` form. These should all be _lpdf/_lpmf.

@adamhaber will fix these files and open a PR  and then you can merge that to your branch. Sorry, it took so long to figure this one. I  was under the impression it's an issue with Fmt, where I have zero knowledge.
