### ISSUE TITLE
Add type (and location?) information to the Mir.

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/stanc3#69]
Currently, the type information for expressions that is collected during type checking is thrown away when passing to the Mir. For some optimizations, like certain algebraic rewrites, this type information is needed, so it is probably a good information to put type annotations on expressions in the Mir.

We want to e.g. do an algebraic simplification
```
 | "log", [BinOp (FunApp ("exp", [x]),Minus,FunApp ("exp", [y]))] ->
    FunApp ("log_diff_exp", [x;y])
```
but can only do that if `x` and `y` are of type `real`, as `log_diff_exp` is otherwise not implemented.

Another example where we even would like (optional) container sizes on expressions is when we want to statically evaluate some calls to `size`, `rows` and `cols`.

**Comment by seantalts** [comment]
unsized types on all expressions? I am wrestling with something that could use that too - particularly indices. But I was thinking of trying to convert to just object-level variants as needed, e.g. a `MatrixSingle` index so we know to use `()` instead of `[]` in codegen. I might still want to do that even if we add type information to the MIR, not sure.

Would you mind giving an example in the top-level comment in this PR that illustrates how it would be useful?

**Comment by VMatthijs** [comment]
Sure. We want to e.g. do an algebraic simplification
```
 | "log", [BinOp (FunApp ("exp", [x]),Minus,FunApp ("exp", [y]))] ->
    FunApp ("log_diff_exp", [x;y])
```
but can only do that if `x` and `y` are of type `real`, as `log_diff_exp` is otherwise not implemented.

Another example where we even would like (optional) container sizes on expressions is when we want to statically evaluate some calls to `size`, `rows` and `cols`.

**Comment by bob-carpenter** [comment]
>  We want to e.g. do an algebraic simplification
> 
>  | "log", [BinOp (FunApp ("exp", [x]),Minus,FunApp ("exp", [y]))] ->
>     FunApp ("log_diff_exp", [x;y])
> 
> but can only do that if x and y are of type real, as log_diff_exp is otherwise not implemented.

Real or assignable to real.  Is there a name for the set of things that can be assigned?  If we had a lattice of types, the inverse relation's a filter.

**Comment by seantalts** [comment]
Gotcha, that makes sense! Seems like we will want type information. Another thought - these peephole optimizations actually seem super similar to the Instruction Selection compiler task. I originally thought we'd have no use for this phase, but I think it's actually the correct place to perform e.g. autovectorization as well as our different backends will have different supported "instructions" (in this case, `log_diff_exp` can be considered an instruction that the Stan math backend supports).

**Comment by seantalts** [comment]
@bob-carpenter you don't need size information for your expression generation do you? by size information I mean the expressions indicating the dimensionality. I assume not - I don't think we have that for most expressions anyway.

**Comment by bob-carpenter** [comment]
Nope.  Don't need sizes.

**Comment by VMatthijs** [comment]
This was addressed by PR https://github.com/stan-dev/stanc3/pull/73

**Comment by VMatthijs** [comment]
@seantalts , @rybern , @bob-carpenter , could you weigh in on whether we should have locations on expressions in the MIR? I think Sean thought that Bob wanted them, but Bob is now saying he doesn't need them. (We definitely want types and adlevels. They have already been super useful in partial evaluation.)

We frequently need to compare expressions for equality and form Sets and Maps of them in optimization and the relevant notion of equality ignores locations. Therefore, from that perspective, not having locations would be most light-weight.

Any thoughts? Thanks guys!

**Comment by bob-carpenter** [comment]
I shouldn't need location in the file for generation.  I think I don't even need block location because I'm just going to assume a typedef for the scalar type in every block where an expression's generated.

In general, when we throw exceptions, we report the line numbers of the enclosing statement.  This has been problematic when we have 

  if (cond) then
    ...
  else
    ...

and the exception is in the evaluation of (cond).  We wind up reporting an error in the entire if/else as that's the smallest containing statement for (cond).  I'm not sure how to fix this problem without having locations in expressions, but even if we had the locations in expressions, I'm not sure how we'd implement them in the code, because the generated code relies on incrementing a static location variable.

**Comment by rybern** [comment]
It does seem like it would be nice to have expression locations for things like error messages. One more low-priority application could be for node labels in a factor graph visualization.

@VMatthijs what sort of hoops do you foresee in ignoring location information for equality? Can we do things like [@compare.ignore] from [here](https://github.com/janestreet/ppx_compare#special-support-for-record-fields), or make Set/Map modules and pass in a custom compare function?

**Comment by VMatthijs** [comment]
The hoops I think would be roughly as you describe. We'd have to figure out how to build sets with a custom comparison rather than the polymorphic compare.

**Comment by seantalts** [comment]
Does compare.ignore not work? If not, what are we using it for / what is it doing?

**Comment by VMatthijs** [comment]
Compare.ignore means that the locations are ignored in the comparison function `compare_expr` which is generated by ppx_deriving. So we can using `compare_expr` to test expressions for equality independent of location. The question though is whether we can use compare_expr as the comparison function for Sets and Maps of expressions and whether we can still make seamless use of all the usual functions on Sets and Maps, like mapping/folding.

**Comment by seantalts** [comment]
Closing - we have this now
