### ISSUE TITLE
Build windows binary

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stanc3#744]
I'm a bit confused the documentation on building Windows binaries. README indicates 

> If Windows binaries are preferred, OCaml for Windows can be used.

while we provide docker image `docker/debian-windows` for windows binary, and I'm under impression cmdstan release uses docker builds. Are the two consistent?

**Comment by rok-cesnovar** [comment]
We build Windoss binaries on Linux. See here https://github.com/stan-dev/stanc3/blob/fd30e88be447d4988521c3c270471dd462966a99/Jenkinsfile-test-binaries#L179

The debian-windows docker uses https://github.com/ocaml-cross/opam-cross-windows

This is the easiest way because building Ocaml natively on Windows is supposed to be very difficult.

**Comment by yizhang-yiz** [comment]
Yes, that's my understanding. Maybe we'll need to update the readme.

**Comment by rok-cesnovar** [comment]
I am working on making github actions scripts to build all required binaries (got stuck with a problem and the worked on other stuff).

I need that to make custom stanc3 binaries for our Ljubljana projects and dont want to abuse Jenkins for those.

 I am guessing you would be interested in that?

**Comment by yizhang-yiz** [comment]
I'm actually thinking about the same thing! For Torsten I'll need to build my own binaries too.

**Comment by rok-cesnovar** [comment]
Will make a PR tomorrow and we can discuss there.
