### ISSUE TITLE
lupdf restrictions and reduce_sum

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/stanc3#753]
The use of lupdfs is currently restricted to the ```model``` block and user defined functions. This makes their use with ```reduce_sum``` a little less intuitive.

For example, modifying the example binomial model:
```
functions {
  real partial_sum(int[] slice_n_redcards,
                   int start, int end,
                   int[] n_games,
                   vector rating,
                   vector beta) {
    return binomial_logit_lupmf(slice_n_redcards |
                               n_games[start:end],
                               beta[1] + beta[2] * rating[start:end]);
  }
}
data {
  int<lower=0> N;
  int<lower=0> n_redcards[N];
  int<lower=0> n_games[N];
  vector[N] rating;
  int<lower=1> grainsize;
}
parameters {
  vector[2] beta;
}
model {

  beta[1] ~ normal(0, 10);
  beta[2] ~ normal(0, 1);

  target += reduce_sum(partial_sum, n_redcards, grainsize,
                       n_games, rating, beta);
}
```

Gives the parsing error:
```
   -------------------------------------------------
     5:                     vector rating,
     6:                     vector beta) {
     7:      return binomial_logit_lupmf(slice_n_redcards |
                    ^
     8:                                 n_games[start:end],
     9:                                 beta[1] + beta[2] * rating[start:end]);
   -------------------------------------------------

Functions with names ending in _lupdf and _lupmf can only be used in the model block or user-defined functions with names ending in _lpdf, _lpmf or _lp.
```

Is this necessary? Shouldn't they be allowed wherever the correspoding ```lpdf```/```lpmf``` is legal?

**Comment by nhuurre** [comment]
> Shouldn't they be allowed wherever the correspoding lpdf/lpmf is legal?

No. The `lupdf`is somewhat nondeterministic because what gets dropped depends on context. The restrictions are in place to forbid corner cases with very counterintuitive behaviour.
The example works if `partial_sum` is renamed to `partial_sum_lpmf`
```stan
functions {
  real partial_sum_lpmf(int[] slice_n_redcards,
                   int start, int end,
                   int[] n_games,
                   vector rating,
                   vector beta) {
    return binomial_logit_lupmf(slice_n_redcards |
                               n_games[start:end],
                               beta[1] + beta[2] * rating[start:end]);
  }
}
data {
  int<lower=0> N;
  int<lower=0> n_redcards[N];
  int<lower=0> n_games[N];
  vector[N] rating;
  int<lower=1> grainsize;
}
parameters {
  vector[2] beta;
}
model {

  beta[1] ~ normal(0, 10);
  beta[2] ~ normal(0, 1);

  target += reduce_sum(partial_sum_lupmf, n_redcards, grainsize,
                       n_games, rating, beta);
}
```

**Comment by andrjohns** [comment]
> The restrictions are in place to forbid corner cases with very counterintuitive behaviour.

Oh interesting, any chance there's a writeup or a comment thread somewhere that covers these?

**Comment by rok-cesnovar** [comment]
I think this writeup by Nico is the best: https://github.com/stan-dev/stanc3/issues/541#issuecomment-632003010 and the following comments. 

Essentially if we allow:

```stan
functions {
  real lprob(real x) {
    return normal_lupdf(x | 0, 1);
  }
}
```
then this is allowed
```stan
transformed parameters {
 real x = lprob(1);
}
```
and propto=true in transformed parameters does not work because of how transformed parameters are implemented in Stan, more details [here](https://discourse.mc-stan.org/t/request-for-final-feedback-user-controlled-unnormalized-propto-distribution-syntax/16029/12?u=rok_cesnovar).

**Comment by nhuurre** [comment]
> I think this writeup by Nico is the best

That's not a writeup, that's an example model. Here's a writeup (by Ni**k**o):

Lpdf is just a function that produces a number. The result has unambiguous mathematically definition. You can call lpdf anywhere a function is allowed, no problem.

Lupdf is like lpdf but without normalizing constants. But what exactly is a "normalizing constant"? Well, it's anything that does not depend on parameters.
For example
```stan
data {
  real x;
  real y;
  real z;
}
parameters {
  real mu;
  real sigma;
}
model {
  target += normal_lupdf(x | mu, sigma);
  target += normal_lupdf(y | mu, 1);
  target += normal_lupdf(z | 0, 1);
}
```
Recall that `normal_lpdf` is equal to `-0.5*((mu-x)/sigma)^2 - log(sigma) - 0.5*log(2*pi)`.
The first lupdf here drops that `log(2*pi)` because that is obviously constant.
The second lupdf drops that but _also_ knows that `log(sigma)` is constant _with respect to the parameters_ and drops that too.
In the last lupdf _nothing_ depends on parameters so it evaluates to _zero_.
So far, makes sense.

What about other program blocks?

It's immediately clear that any lupdf appearing `transformed data` block is always constant and thus pretty much a no-op.

A lupdf in the `generated quantities` block _can_ depend on parameters but actually _actually_ the real definition of "normalizing constant" in the math backend is based on whether the autodiff is involved and `generated quantities` does not need autodiff.
So in fact everything is constant again.

Now, that's a bit weird but not terrible. So what if lupdf is always zero? It's useless but is that really a reason to _forbid_ it outside of `model` and ... `transformed parameters`.
Oh, `transformed parameters` is where it gets confusing. A model like
```stan
parameters {
  real x;
}
transformed parameters {
  real lp = normal_lupdf(x|0,1);
}
model {
  target += lp;
}
```
produces the same C++ code as
```stan
parameters {
  real x;
}
model {
  real lp = normal_lupdf(x|0,1);
  target += lp;
}
generated quantities {
  real lp = normal_lupdf(x|0,1);
}
```
And looks reasonable until you realize that those lupdf return different values. Despite the model clearly saying `target` is just `lp` and nothing else, `lp` in the output is not equal to `lp__`.
That's just a simple example. I expect that often the lupdf would be hidden inside a function.

At this point we have four options

1. tell people to debug using `print()` and _not_ assume transformed parameters don't secretly change inside the model block. 
2. have the compiler automatically find all lupdf uses and check that they can't cause problems
3. mark all functions that _could_ invoke lupdf with a special suffix
4. change how generated quantities are computed to use the autodiff anyway

I chose 3 and the suffix is `_lpdf`.

**Comment by rok-cesnovar** [comment]
> Here's a writeup (by Niko):

I apologize for misspelling your name.

Thanks for the write-up. I was thinking for some time doing the initial implementation that 2 might work, but that would be too bug-prone and a lot of traversing the UDFs. And its not worth it, especially given that the only thing that we need for 3 is that the UDF suffix has to be _lpdf.

cc @bbbales2 this is probably a bit too much detail for the lupdf docs but maybe we can include some of this? idk.

**Comment by nhuurre** [comment]
No worries about misspellings, I was unsure whether it was worth mentioning at all.

Also unsure on how much of this belongs in the docs. The point of lupdf restrictions was that the user does not need to worry about any of this.

**Comment by bbbales2** [comment]
> I was unsure whether it was worth mentioning at all.

I wrote your name down on my todo list this morning and was wondering which way to write it lol.

> but maybe we can include some of this?

Wooof yeah need to get back the docs on that. Tomorrow.

**Comment by andrjohns** [comment]
Thanks all, this makes sense now. If this gets included in the docs then I'd be in favour of the parser error including a link to that documentation
