### ISSUE TITLE
Identifier clashes with model name.

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stanc3#781]
This might be intentional, but at the same time the warning message says `the new compiler did not work like we hoped`. If the behavior is intentional the semantic error message could be more clear to indicate that the user should rename the stan code file.

The model code
```
parameters {
  real f2;
}
model {
  f2 ~ normal(0,1);
}
```
The model code is in a file `f2.stan`. Using `rstan_2.21.2` 
```
fit2 <- stan(file = "f2.stan")
```
Causes message
```
When you compile models, you are also contributing to development of the NEXT
Stan compiler. In this version of rstan, we compile your model as usual, but
also test our new compiler on your syntactically correct model. In this case,
the new compiler did not work like we hoped. By filing an issue at
https://github.com/stan-dev/stanc3/issues with your model
or a minimal example that shows this warning you will be contributing
valuable information to Stan and ensuring your models continue working. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages()
 or by first calling rstan_options(javascript = FALSE).

Semantic error in 'string', line 2, column 7 to column 9:

Identifier 'f2' clashes with model name.
```

**Comment by rok-cesnovar** [comment]
Thanks. I think we should find a way to remove this restriction.

This was reported previously https://github.com/stan-dev/stanc3/issues/751 so it seems its not that unusual.

**Comment by rok-cesnovar** [comment]
The simplest solution would be to generate the C++ class with the "__" suffix that is not allowed for identifiers. What say you @seantalts @nhuurre et al? 

Binary stanc version adds a _model suffix to the name, which makes this less likely, but can still happen. stanc.js currently does not.

**Comment by wds15** [comment]
Whatever the solution is, at the end the user should be able to fully control the model user namespace if requested which is needed for C++ extensions.

**Comment by rok-cesnovar** [comment]
I am not sure I understand what you mean? Do you mean that external C++ would still work as before (apart from the added __ suffix for example)?

**Comment by rok-cesnovar** [comment]
Let me give a bit more context to this issue. 

Stanc3 names the C++ model representing the Stan model as `filename_model` or `filename` in some cases (this should be unified to one case but that is a different issue). Lets just take the case where its just `filename`.

So if I make a `t.stan` file and compile stanc3 will generate:

```cpp
class t final : public model_base_crtp<t> {

 private:
...
```
If our model has a `t` variable it will fail at the C++ level if I lift this restriction.

```stan
data {
  vector[5] t;
}
...
```
will result in
```
examples/test/t.hpp:68:32: error: field ‘Eigen::Matrix<double, -1, 1> t_namespace::t::t’ with same name as class [-fpermissive]
   68 |   Eigen::Matrix<double, -1, 1> t;
```                            ^

Stanc2 had the exact same restriction with a different text:

``` 
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Duplicate declaration of variable, name=t; attempt to redeclare as vector in data; previously declared as ill-formed in model name
 error in 'examples/test/t.stan' at line 2, column 13
``` 
This never surfaced with rstan because rstan saves the model in a temp file with a random name (a234bd23.stan) and obviously no one names their variables that way.

stanc3 in most cases adds the _model suffix to the model name and that makes it less common (naming a variable x_model is probably not that common). Adding a __ suffix would make a clash impossible as a variable identifier can not have that suffix. 

Another solution is to just clarify the error text and be done with it.

**Comment by rok-cesnovar** [comment]
This is not an issue with rstan 2.26.1 (from the 2.26 PR). 

I think was just a problem with the temporary stanc3-compatibility-checker in current rstan 2.21.

Closing.
